# Generated by Django 5.1.7 on 2025-03-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytono_failai', '0002_booking_message_booking_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Laiško tema')),
                ('body', models.TextField(verbose_name='Laiško turinys (naudok {{ user }}, {{ date }})')),
            ],
        ),
    ]
