# Generated by Django 5.1.7 on 2025-03-17 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytono_failai', '0003_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(verbose_name='Data')),
                ('slot_time', models.TimeField(verbose_name='Laikas')),
            ],
            options={
                'ordering': ['slot_date', 'slot_time'],
                'unique_together': {('slot_date', 'slot_time')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytono_failai.availableslot')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
