# Generated by Django 5.1.7 on 2025-03-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytono_failai', '0004_availableslot_reservation_delete_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='available_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytono_failai.availableslot'),
        ),
    ]
